### ISSUE TITLE
[Request] Example Usage

### ISSUE THREAD

**Issue by tolu360** [gijoehosaphat/react-native-realtime-pusher#2]
Hello @gijoehosaphat, thank you for sharing this - looks fully-featured to me (reading through the source). This is not, by any means, an issue; it is more like a request - please can you beef up the `Example Usage` section on the `README`?

Thank you!

**Comment by gijoehosaphat** [comment]
I've beefed it up per your request! Let me know if you have any problems.

**Comment by tolu360** [comment]
Thank you @gijoehosaphat, have since looked at the source for usage, available methods and their signatures - I was able to find my way through. I was going to send a PR for the readme but got carried away with work. I would let you know if I need further assistance.

Thank you for putting this together.
